{
  "dns": {
    "enable": true,
    "ipv6": false,
    "nameserver": [
      "223.5.5.5",
      "119.29.29.29"
    ],
    "fallback": [
      "https://1.1.1.1/dns-query",
      "https://8.8.8.8/dns-query"
    ],
    "fallback-filter": {
      "geoip": true,
      "geoip-code": "CN"
    }
  },
  "proxy-groups": [
    {
      "name": "NETWORK",
      "type": "select",
      "proxies": [
        "HK",
        "DIRECT",
        "SG",
        "TW",
        "JP",
        "US"
      ]
    },
    {
      "name": "US",
      "type": "select",
      "include-all": true,
      "filter": "(?i)(\\bUS\\b|USA|United\\s*States|美国|洛杉矶|圣何塞|西雅图|达拉斯|纽约|c87s1|c87s2|c87s3|US\\d+)"
    },
    {
      "name": "JP",
      "type": "select",
      "include-all": true,
      "filter": "(?i)(\\bJP\\b|Japan|日本|东京|大阪|埼玉|c87s4|JP\\d+)"
    },
    {
      "name": "HK",
      "type": "url-test",
      "include-all": true,
      "filter": "(?i)(\\bHK\\b|Hong\\s*Kong|香港|HK\\d+)",
      "url": "https://cp.cloudflare.com/generate_204",
      "interval": 600,
      "tolerance": 100,
      "lazy": true
    },
    {
      "name": "SG",
      "type": "url-test",
      "include-all": true,
      "filter": "(?i)(\\bSG\\b|Singapore|新加坡|SG\\d+)",
      "url": "https://cp.cloudflare.com/generate_204",
      "interval": 600,
      "tolerance": 100,
      "lazy": true
    },
    {
      "name": "TW",
      "type": "url-test",
      "include-all": true,
      "filter": "(?i)(\\bTW\\b|Taiwan|台湾|台北|TW\\d+)",
      "url": "https://cp.cloudflare.com/generate_204",
      "interval": 600,
      "tolerance": 100,
      "lazy": true
    }
  ],
  "rules": [
    "IP-CIDR,10.0.0.0/8,DIRECT,no-resolve",
    "IP-CIDR,172.16.0.0/12,DIRECT,no-resolve",
    "IP-CIDR,192.168.0.0/16,DIRECT,no-resolve",
    "DOMAIN-SUFFIX,mask.icloud.com,US",
    "DOMAIN-SUFFIX,mask-h2.icloud.com,US",
    "DOMAIN-SUFFIX,mask-api.icloud.com,US",
    "DOMAIN-SUFFIX,mask.apple-dns.net,US",
    "DOMAIN-SUFFIX,guzzoni.apple.com,US",
    "DOMAIN-SUFFIX,smoot.apple.com,US",
    "DOMAIN-SUFFIX,chatgpt.com,US",
    "DOMAIN-SUFFIX,ws.chatgpt.com,US",
    "DOMAIN-SUFFIX,openai.com,US",
    "DOMAIN-SUFFIX,ios.chat.openai.com,US",
    "DOMAIN-SUFFIX,oaistatic.com,US",
    "DOMAIN-SUFFIX,oaiusercontent.com,US",
    "DOMAIN-SUFFIX,cdn.openai.com,US",
    "DOMAIN-SUFFIX,files.openai.com,US",
    "DOMAIN-SUFFIX,openaiapi-site.azureedge.net,US",
    "DOMAIN-SUFFIX,api.openai.com,US",
    "DOMAIN-SUFFIX,chat.openai.com,US",
    "DOMAIN-SUFFIX,chatgptusercontent.com,US",
    "DOMAIN-SUFFIX,auth0.com,US",
    "DOMAIN-SUFFIX,auth.openai.com,US",
    "DOMAIN-SUFFIX,sora.com,US",
    "DOMAIN-SUFFIX,sora.chat,US",
    "DOMAIN-SUFFIX,openai.azureedge.net,US",
    "DOMAIN-SUFFIX,music.apple.com,NETWORK",
    "DOMAIN-SUFFIX,applemusic.com,NETWORK",
    "DOMAIN-SUFFIX,tv.apple.com,NETWORK",
    "DOMAIN-SUFFIX,apple.news,NETWORK",
    "DOMAIN-SUFFIX,news.apple.com,NETWORK",
    "DOMAIN-SUFFIX,itunes.apple.com,NETWORK",
    "DOMAIN-SUFFIX,apps.apple.com,NETWORK",
    "DOMAIN-SUFFIX,mzstatic.com,NETWORK",
    "DOMAIN-SUFFIX,connectivitycheck.gstatic.com,NETWORK",
    "DOMAIN-SUFFIX,gstatic.com,NETWORK",
    "DOMAIN-SUFFIX,googleapis.com,NETWORK",
    "DOMAIN-SUFFIX,gemini.google.com,NETWORK",
    "DOMAIN-SUFFIX,bard.google.com,NETWORK",
    "DOMAIN-SUFFIX,generativelanguage.googleapis.com,NETWORK",
    "DOMAIN-SUFFIX,proactivebackend-pa.googleapis.com,NETWORK",
    "DOMAIN-SUFFIX,ai.google.dev,NETWORK",
    "DOMAIN-SUFFIX,google.com,NETWORK",
    "DOMAIN-SUFFIX,googleusercontent.com,NETWORK",
    "DOMAIN-SUFFIX,googlevideo.com,NETWORK",
    "DOMAIN-SUFFIX,ggpht.com,NETWORK",
    "DOMAIN-SUFFIX,api.telegram.org,NETWORK",
    "IP-CIDR,91.108.0.0/16,NETWORK,no-resolve",
    "IP-CIDR,149.154.160.0/20,NETWORK,no-resolve",
    "DOMAIN-SUFFIX,t.me,NETWORK",
    "DOMAIN-SUFFIX,telegram.org,NETWORK",
    "DOMAIN-SUFFIX,telegram.me,NETWORK",
    "DOMAIN-SUFFIX,telegram.dog,NETWORK",
    "DOMAIN-SUFFIX,tdesktop.com,NETWORK",
    "DOMAIN-SUFFIX,telegra.ph,NETWORK",
    "DOMAIN-SUFFIX,graph.org,NETWORK",
    "DOMAIN-SUFFIX,tg.dev,NETWORK",
    "DOMAIN-SUFFIX,tx.me,NETWORK",
    "DOMAIN-SUFFIX,turrit.com,NETWORK",
    "DOMAIN-SUFFIX,turrit.app,NETWORK",
    "DOMAIN-SUFFIX,whatsapp.com,NETWORK",
    "DOMAIN-SUFFIX,whatsapp.net,NETWORK",
    "DOMAIN-SUFFIX,wa.me,NETWORK",
    "DOMAIN-SUFFIX,youtube.com,NETWORK",
    "DOMAIN-SUFFIX,ytimg.com,NETWORK",
    "DOMAIN-SUFFIX,paypal.com,US",
    "DOMAIN-SUFFIX,paypalobjects.com,US",
    "DOMAIN-SUFFIX,pikpak.com,NETWORK",
    "DOMAIN-SUFFIX,pornhub.com,NETWORK",
    "DOMAIN-SUFFIX,phncdn.com,NETWORK",
    "DOMAIN-SUFFIX,phprcdn.com,NETWORK",
    "DOMAIN-SUFFIX,xvideos.com,NETWORK",
    "DOMAIN-SUFFIX,xvcdn.com,NETWORK",
    "DOMAIN-SUFFIX,xnxx.com,NETWORK",
    "DOMAIN-SUFFIX,redtube.com,NETWORK",
    "DOMAIN-SUFFIX,tube8.com,NETWORK",
    "DOMAIN-SUFFIX,youporn.com,NETWORK",
    "DOMAIN-SUFFIX,spankbang.com,NETWORK",
    "DOMAIN-SUFFIX,sexvideo.com,NETWORK",
    "DOMAIN-SUFFIX,hqporner.com,NETWORK",
    "GEOIP,CN,DIRECT",
    "MATCH,NETWORK"
  ]
}
